services:
  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./backend
        target: /var/www
      - type: volume
        target: /var/www/vendor
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    working_dir: /var/www

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        target: /app/node_modules
    container_name: react-frontend

volumes:
  mysqldata:
