services:
  - type: web
    name: laravel-backend
    env: docker
    repo: https://github.com/markvanmeerten/app-docker-basic-project-test-1
    rootDir: backend
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          name: mysql-db
          property: host
      - key: DB_PORT
        fromService:
          name: mysql-db
          property: port
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: laravel
      - key: DB_PASSWORD
        value: secret

  - type: private
    name: mysql-db
    env: docker
    image: mysql:8
    plan: free
    envVars:
      - key: MYSQL_DATABASE
        value: laravel
      - key: MYSQL_USER
        value: laravel
      - key: MYSQL_PASSWORD
        value: secret
      - key: MYSQL_ROOT_PASSWORD
        value: root

  - type: web
    name: react-frontend
    env: static
    repo: https://github.com/markvanmeerten/app-docker-basic-project-test-1
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
